name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  calc-version:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.fullSemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Calculate version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

  build-web:
    name: Build web UI
    needs: [calc-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install Node.js dependencies
        run: npm ci
        working-directory: ./html

      - name: Build web UI
        run: npm run build
        working-directory: ./html

      - name: Package web UI
        run: pushd html/dist && zip -9 -r ../webui.zip * && popd && ls -la

      - name: Upload web UI to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webui.zip
          path: html/webui.zip

  build-app:
    strategy:
      matrix:
        platform: [linux-amd64]
        include:
          - platform: linux-amd64
            runner: buildjet-4vcpu-ubuntu-2204

    name: Build Porla (${{ matrix.platform }})
    needs: [build-web, calc-version]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Download web UI artifact
        uses: actions/download-artifact@v3
        with:
          name: webui.zip
          path: html/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: GITVERSION_SEMVER=${{ needs.calc-version.outputs.semVer }}
          context: .
          load: true
          tags: porla

      - name: Copy Porla binary from image
        run: |
          docker create --name tmp porla
          docker cp tmp:/usr/bin/porla /tmp/porla
          docker rm -f tmp

      - name: Upload Porla binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: porla-${{ matrix.platform }}
          path: /tmp/porla
